version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-manish-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: manishrootpassword
      MYSQL_DATABASE: manishDatabase
      MYSQL_USER: Manish
      MYSQL_PASSWORD: manishpwd
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: